### PR TITLE
Added a logo and favicon !

### PR DESCRIPTION
**Pull request by Geshii**

### CODE REVIEW

**Comment by Niweera** [comment]
Hey @Geshii, thank you for creating this pull request! Have a wonderful day...

**Comment by Geshii** [comment]
> Hey @Geshii, thank you for creating this pull request! Have a wonderful day...

np ! have a good day too ! Tell me what you think about this when you can ^^'

**Review by Niweera — CHANGES_REQUESTED** [review]
Nice work @Geshii. Superb. Thanks for your contribution. However, can you rename your logo as your username so that others can also contribute without any merge conflicts. I would like to advise you not to change anything in the `/public/index.html` file so that it will not affect other contributions. You can just include the logo in the public folder and commit again. You don't have to see the logo as the current favicon. We'll set the best logo as our favicon. Seems reasonable right? 😁

**Comment by Geshii** [comment]
Yes ofc ! Will change that later

**Comment by Niweera** [comment]
> Yes ofc ! Will change that later

Thanks @Geshii

**Pull request closed without merging**
