### PR TITLE
navbar_added

### PR DESCRIPTION
**Pull request by MukulTan10**
Addressing issue #4 
Branch-name = navbar

Added Navbar for homepage

### CODE REVIEW

**Comment by Niweera** [comment]
Hey @MukulTan10, thank you for creating this pull request! Have a wonderful day...

**Comment by MukulTan10** [comment]
hey , issue is arrissing cause of changing header in route with new navbar and replacing it with new, you can review the code , if you would like to replace content of routes.php to old one , i can make another push for same

**Comment by MukulTan10** [comment]
hye the conflict in routes file is because of replacing the old header with new navbar, you can review it and if you want i can replace it to old file and warning is because of image that is not used anywhere as much i seen .you can review if you feel any changes need to be made please write back

**Comment by Niweera** [comment]
Hi @MukulTan10,
It seems like some issue with your code which throws a warning by our Deepcode bot. I would like to advise you to use Functional components instead of Class components. Can you change the [index.js file](https://github.com/Niweera/cinesimile/blob/6c6471913810ea8990ef52f8834f2250450b6184/src/components/Navbar/index.js#L55) to a functional based component? Thanks in advance. Have a nice day. 
BTW, I resolved the merge conflict and when you fixed the issue I will merge it into the master branch.

**Comment by MukulTan10** [comment]
hey , i have resolved the issue , warning issue we are getting is because of search bar ( i have take the pull of merge branch) , can you ask the developer who made the search to resolve this,attacing you warning description in this too . if i can do anything please let me know
Untitled2

**Comment by Niweera** [comment]
> hey , i have resolved the issue , warning issue left is because of search bar ( i have take the pull of merge branch) , can you ask the developer who made the search to resolve this,attaching warning description in this too . if i can do anything please let me know
> Untitled2

You haven't resolved the issue that I have asked for. You have to convert the class component to a functional component. 

Please update this file [index.js](https://github.com/MukulTan10/cinesimile/blob/navbar/src/components/Navbar/index.js) and commit again. 

Before doing that, I advise you to sync your fork. Use the following lines.

```shell
$ git pull upstream master
```

**Comment by MukulTan10** [comment]
hey , i have converted the class component to functional

**Review by Niweera — APPROVED** [review]
Nice work. Thanks for contributing to our project. Keep up the good work!
BTW, Happy Hacktoberfest!!! 😎

**Pull request merged**
